// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: swbf.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_swbf_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_swbf_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_swbf_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_swbf_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_swbf_2eproto;
namespace swbf {
class Interact;
struct InteractDefaultTypeInternal;
extern InteractDefaultTypeInternal _Interact_default_instance_;
}  // namespace swbf
PROTOBUF_NAMESPACE_OPEN
template<> ::swbf::Interact* Arena::CreateMaybeMessage<::swbf::Interact>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace swbf {

// ===================================================================

class Interact final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:swbf.Interact) */ {
 public:
  inline Interact() : Interact(nullptr) {}
  ~Interact() override;
  explicit constexpr Interact(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Interact(const Interact& from);
  Interact(Interact&& from) noexcept
    : Interact() {
    *this = ::std::move(from);
  }

  inline Interact& operator=(const Interact& from) {
    CopyFrom(from);
    return *this;
  }
  inline Interact& operator=(Interact&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Interact& default_instance() {
    return *internal_default_instance();
  }
  static inline const Interact* internal_default_instance() {
    return reinterpret_cast<const Interact*>(
               &_Interact_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Interact& a, Interact& b) {
    a.Swap(&b);
  }
  inline void Swap(Interact* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Interact* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Interact* New() const final {
    return new Interact();
  }

  Interact* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Interact>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Interact& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Interact& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Interact* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "swbf.Interact";
  }
  protected:
  explicit Interact(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTextMessagesFieldNumber = 1,
  };
  // repeated string textMessages = 1;
  int textmessages_size() const;
  private:
  int _internal_textmessages_size() const;
  public:
  void clear_textmessages();
  const std::string& textmessages(int index) const;
  std::string* mutable_textmessages(int index);
  void set_textmessages(int index, const std::string& value);
  void set_textmessages(int index, std::string&& value);
  void set_textmessages(int index, const char* value);
  void set_textmessages(int index, const char* value, size_t size);
  std::string* add_textmessages();
  void add_textmessages(const std::string& value);
  void add_textmessages(std::string&& value);
  void add_textmessages(const char* value);
  void add_textmessages(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& textmessages() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_textmessages();
  private:
  const std::string& _internal_textmessages(int index) const;
  std::string* _internal_add_textmessages();
  public:

  // @@protoc_insertion_point(class_scope:swbf.Interact)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> textmessages_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_swbf_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Interact

// repeated string textMessages = 1;
inline int Interact::_internal_textmessages_size() const {
  return textmessages_.size();
}
inline int Interact::textmessages_size() const {
  return _internal_textmessages_size();
}
inline void Interact::clear_textmessages() {
  textmessages_.Clear();
}
inline std::string* Interact::add_textmessages() {
  std::string* _s = _internal_add_textmessages();
  // @@protoc_insertion_point(field_add_mutable:swbf.Interact.textMessages)
  return _s;
}
inline const std::string& Interact::_internal_textmessages(int index) const {
  return textmessages_.Get(index);
}
inline const std::string& Interact::textmessages(int index) const {
  // @@protoc_insertion_point(field_get:swbf.Interact.textMessages)
  return _internal_textmessages(index);
}
inline std::string* Interact::mutable_textmessages(int index) {
  // @@protoc_insertion_point(field_mutable:swbf.Interact.textMessages)
  return textmessages_.Mutable(index);
}
inline void Interact::set_textmessages(int index, const std::string& value) {
  textmessages_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:swbf.Interact.textMessages)
}
inline void Interact::set_textmessages(int index, std::string&& value) {
  textmessages_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:swbf.Interact.textMessages)
}
inline void Interact::set_textmessages(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  textmessages_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:swbf.Interact.textMessages)
}
inline void Interact::set_textmessages(int index, const char* value, size_t size) {
  textmessages_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:swbf.Interact.textMessages)
}
inline std::string* Interact::_internal_add_textmessages() {
  return textmessages_.Add();
}
inline void Interact::add_textmessages(const std::string& value) {
  textmessages_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:swbf.Interact.textMessages)
}
inline void Interact::add_textmessages(std::string&& value) {
  textmessages_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:swbf.Interact.textMessages)
}
inline void Interact::add_textmessages(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  textmessages_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:swbf.Interact.textMessages)
}
inline void Interact::add_textmessages(const char* value, size_t size) {
  textmessages_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:swbf.Interact.textMessages)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Interact::textmessages() const {
  // @@protoc_insertion_point(field_list:swbf.Interact.textMessages)
  return textmessages_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Interact::mutable_textmessages() {
  // @@protoc_insertion_point(field_mutable_list:swbf.Interact.textMessages)
  return &textmessages_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace swbf

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_swbf_2eproto
