#pragma once
enum class ILobbyMemberStateChange {
    LOBBY_MEMBER_STATE_CHANGED_ENTERED = 0x0001,
    LOBBY_MEMBER_STATE_CHANGED_LEFT = 0x0002,
    LOBBY_MEMBER_STATE_CHANGED_DISCONNECTED = 0x0004,
    LOBBY_MEMBER_STATE_CHANGED_KICKED = 0x0008,
    LOBBY_MEMBER_STATE_CHANGED_BANNED = 0x0010
};

